### ISSUE TITLE
Using qmake instead CMake

### ISSUE THREAD

**Issue by skajter** [vt4a2h/uml-tool#2]
I get idea that CMake is used and why ... but is any chance to use qmake?

As you already have pro files, is not that many work to 'link to qt stack'?

**Comment by vt4a2h** [comment]
CMake is used just for expiriment. Qmake is the main build system for this project. You can simply open uml-tool.pro in QtCreator (as I usualy do) and build. Ditto for tests.

**Comment by skajter** [comment]
Also i can confirm that under VS2013/VS2015 is unable to build :)

So quick note can be add into readme: If you like to build under Windows use MinGW compiler.

VS2015 have some features from C++14, but most of them are not working with current code base.
I will not create any issues about that, as like you mentioned in other bug - you using linux/gcc - but in my opinion is worth to mention that in readme ;)

PS: I will try to make some more testing/build on Windows :)

**Comment by vt4a2h** [comment]
Well, to be honest, I've never built it on Windows, but it doesn't mean that I strongly against this system. It'd be great to add Windows support to some of build system (qmake or CMake) and probably configure CI (https://www.appveyor.com/). Feel free to start looking into this issue :)
Also I probably accidentally used some gnu extensions (I tried don't do that, but who knows)... They should be eliminated of course.
I'll update readme.

**Comment by skajter** [comment]
Readme updated, that clarify what is where ... so this one can be closed ;)
